Repository SAMMaru5/SAMMaruServer, pull requests merged in 2022-05, with the labels that each got.

#2 refactor : change return type wild card to specific type
  src/main/java/com/sammaru5/sammaru/controller/comment/CommentController.java
Labels: API, Refactor

#4 [fix] change authentication to custom auth user annotation (#3)
  src/main/java/com/sammaru5/sammaru/controller/article/ArticleController.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
Labels: bug

#10 fix : add sub file upload api and change authority original file down…
  src/main/java/com/sammaru5/sammaru/controller/FileController.java
  src/main/java/com/sammaru5/sammaru/controller/article/ArticleController.java
  src/main/java/com/sammaru5/sammaru/domain/FileDB.java
  src/main/java/com/sammaru5/sammaru/dto/ResponseFile.java
  src/main/java/com/sammaru5/sammaru/repository/FileDBRepository.java
  src/main/java/com/sammaru5/sammaru/service/file/FileStorageService.java
Labels: bug

#11 fix : change authority in proper api that file download api (#5)
  src/main/java/com/sammaru5/sammaru/controller/article/ArticleController.java
Labels: bug

#13 feat : 기수별 멤버 조회 (#6)
  src/main/java/com/sammaru5/sammaru/controller/user/UserController.java
  src/main/java/com/sammaru5/sammaru/domain/UserEntity.java
  src/main/java/com/sammaru5/sammaru/dto/UserDTO.java
  src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
Labels: API, FEAT

#14 feat : When viewing articles, related files are also searched (#6)
  src/main/java/com/sammaru5/sammaru/domain/ArticleEntity.java
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
Labels: FEAT
