Repository SAMMaru5/SAMMaruServer, pull requests merged in 2022-06, with the labels that each got.

#20 [REFACTOR] Article, File 엔티티 간 연관관계 메서드 생성 및 Article과 File fetch join 메서드 생성
  src/main/java/com/sammaru5/sammaru/domain/ArticleEntity.java
  src/main/java/com/sammaru5/sammaru/domain/FileEntity.java
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
Labels: FIX, REFACTOR

#33 fix : ArticleEntity에서 ArticleDTO로의 변환 과정에서 일부 필드가 적용되지 않는 문제 수정(#32)
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
Labels: BUG, FIX

#35 fix : file이 존재하지 않는 article 조회 시 조회가 안되는 문제 수정
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
Labels: BUG, FIX

#36 [REFACTOR] CustomException 추가 및 Enum으로 ErrorCode 관리하도록 변경
  src/main/java/com/sammaru5/sammaru/exception/CustomException.java
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/exception/InvalidRefreshTokenException.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentSearchService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileStatusService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
  src/main/java/com/sammaru5/sammaru/web/controller/exception/ExceptionController.java
Labels: REFACTOR

#37 refactor : 모든 Entity id 필드의 DB column 명 변경 및 Entity명 간소화
  src/main/java/com/sammaru5/sammaru/config/security/CustomUserDetailsService.java
  src/main/java/com/sammaru5/sammaru/config/security/UserDetail.java
  src/main/java/com/sammaru5/sammaru/domain/Article.java
  src/main/java/com/sammaru5/sammaru/domain/Board.java
  src/main/java/com/sammaru5/sammaru/domain/Comment.java
  src/main/java/com/sammaru5/sammaru/domain/File.java
  src/main/java/com/sammaru5/sammaru/domain/Schedule.java
  src/main/java/com/sammaru5/sammaru/domain/User.java
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/repository/BoardRepository.java
  src/main/java/com/sammaru5/sammaru/repository/CommentRepository.java
  src/main/java/com/sammaru5/sammaru/repository/FileRepository.java
  src/main/java/com/sammaru5/sammaru/repository/ScheduleRepository.java
  src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleStatusService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardStatusService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentSearchService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileStatusService.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleSearchService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserStatusService.java
  src/main/java/com/sammaru5/sammaru/web/controller/TestController.java
  src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
  src/main/java/com/sammaru5/sammaru/web/dto/AnnouncementDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/BoardDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/FileDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/ScheduleDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
  src/main/java/com/sammaru5/sammaru/web/request/BoardRequest.java
Labels: REFACTOR

#22 refactor : Article Service 계층에서 if문을 통한 Optional 객체의 유무 판단을 orElseThrow로 변환
  src/main/java/com/sammaru5/sammaru/domain/Board.java
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/dto/BoardDTO.java
Labels: REFACTOR

#41 refactor: @CreationTimestamp 를 @CreatedDate로 변경하면서 JpaAuditing 추가
  src/main/java/com/sammaru5/sammaru/SammaruApplication.java
  src/main/java/com/sammaru5/sammaru/domain/Article.java
  src/main/java/com/sammaru5/sammaru/domain/BaseTime.java
  src/main/java/com/sammaru5/sammaru/domain/Board.java
  src/main/java/com/sammaru5/sammaru/domain/Comment.java
  src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
Labels: REFACTOR

#40 feat : 중요 게시판 삭제할때 Exception 발생
  src/main/java/com/sammaru5/sammaru/domain/IndelibleBoardName.java
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardRemoveService.java
Labels: FEAT
