Repository SAMMaru5/SAMMaruServer, pull requests merged in 2022-10, with the labels that each got.

#117 refactor: 코드 가독성 향상을 위한 리팩토링
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentSearchService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
Labels: REFACTOR

#123 fix: 게시글 삭제하기전 관련 댓글부터 삭제하도록 수정
  src/main/java/com/sammaru5/sammaru/repository/CommentRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/test/java/com/sammaru5/sammaru/service/article/ArticleRemoveServiceTest.java
Labels: BUG

#122 refactor: 게시글 생성 및 수정 API의 반환을 DTO로 변경
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
Labels: REFACTOR

#126 refactor: Service에서 정적 팩토리 메서드를 통해 객체 생성하도록 변경
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentModifyService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/BoardDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/ScheduleDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
Labels: REFACTOR

#129 refactor: 엔티티 수정 시, Dirty Checking 적용
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
Labels: REFACTOR

#130 refactor: 게시판 조회 서비스 이름 변경
  src/main/java/com/sammaru5/sammaru/service/board/BoardSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
Labels: REFACTOR

#125 refactor: 사진, 파일을 Docker Volume을 통해 공유하도록 변경
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileStatusService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: REFACTOR

#133 fix : 정보수정 API 에서 student_id 수정 가능하게 변경
  src/main/java/com/sammaru5/sammaru/domain/User.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/web/request/UserRequest.java
Labels: FIX, API

#137 feat: 일정 수정 API 추가
  src/main/java/com/sammaru5/sammaru/domain/Schedule.java
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleModifyService.java
  src/main/java/com/sammaru5/sammaru/web/controller/schedule/ScheduleController.java
Labels: API, FEAT

#140 refactor: Repository 어노테이션 생략
  src/main/java/com/sammaru5/sammaru/repository/BoardRepository.java
  src/main/java/com/sammaru5/sammaru/repository/ScheduleRepository.java
Labels: REFACTOR

#136 feat: 게시판 수정 API 추가
  src/main/java/com/sammaru5/sammaru/domain/Board.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardModifyService.java
  src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
Labels: API, FEAT

#138 fix: 댓글 및 일정 요청 파라미터 체크 위해 사용되는 어노테이션 추가
  src/main/java/com/sammaru5/sammaru/web/request/CommentRequest.java
  src/main/java/com/sammaru5/sammaru/web/request/ScheduleRequest.java
Labels: FIX

#148 fix: 게시글 및 일정 삭제 서비스에 예외처리 추가
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRemoveService.java
Labels: FIX

#150 fix: 배포 서버 url을 allowedOrigins에 추가
  src/main/java/com/sammaru5/sammaru/config/MvcConfig.java
Labels: FIX

#146 refactor: 게시판 등록 서비스내의 트랜잭션 단위안에서 예외처리하도록 설정
  src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
Labels: REFACTOR

#142 refactor: 성능 향상을 위한 @Transaction(readOnly=true) 작성
  src/main/java/com/sammaru5/sammaru/service/article/ArticleLikeService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardSearchService.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserLogoutService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserStatusService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserTempPasswordService.java
Labels: REFACTOR

#154 fix: 테스트 환경 수정
  build.gradle
  src/test/java/com/sammaru5/sammaru/service/article/ArticleSearchServiceTest.java
  src/test/resources/application.yml
Labels: FIX
