Repository SAMMaru5/SAMMaruServer, pull requests merged in 2022-07, with the labels that each got.

#43 feat : 유저의 역할마다 사용할 수 있는 기능 제한
  src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
  src/main/java/com/sammaru5/sammaru/util/OverAdminRole.java
  src/main/java/com/sammaru5/sammaru/util/OverMemberRole.java
  src/main/java/com/sammaru5/sammaru/util/OverTempRole.java
  src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
  src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
  src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
  src/main/java/com/sammaru5/sammaru/web/controller/schedule/ScheduleController.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
  src/main/java/com/sammaru5/sammaru/web/request/RoleRequest.java
Labels: FEAT

#48 refactor : Article과 File에 영속성 전이 적용 및 고아 객체 제거 설정 사용, 더이상 사용하지 않는 fileRegisterService와 fileRemoveService 코드 삭제 (#47)
  src/main/java/com/sammaru5/sammaru/domain/Article.java
  src/main/java/com/sammaru5/sammaru/domain/FileDB.java
  src/main/java/com/sammaru5/sammaru/repository/FileDBRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/file/FileStorageService.java
  src/main/java/com/sammaru5/sammaru/web/controller/FileController.java
  src/main/java/com/sammaru5/sammaru/web/controller/TestController.java
  src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
Labels: FIX, REFACTOR

#49 feat : userId로 단일 회원 정보 조회 API 추가
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
  src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
Labels: API, FEAT

#51 fix : 게시글 조회 시 첨부된 파일과 작성자를 한번에 볼 수 있도록 Query 수정
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
Labels: FIX, REFACTOR

#52 feat: 임시 비밀번호를 메일로 받아볼 수 있는 기능 추가
  build.gradle
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserTempPasswordService.java
  src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
  src/main/resources/application.yml
Labels: API, FEAT

#54 feat : 관리자 권한의 username으로 회원 정보 조희 기능 추가
  .gitignore
  src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
Labels: API, FEAT

#57 fix : 기본 생성자가 없는 DTO의 연속 조회가 일어날시 발생하는 500 에러 해결 (#56)
  src/main/java/com/sammaru5/sammaru/web/dto/AnnouncementDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/BoardDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/JwtDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/ResponseFile.java
  src/main/java/com/sammaru5/sammaru/web/dto/ScheduleDTO.java
  src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
Labels: BUG, FIX

#55 feat: 게시글 검색 기능 추가
  src/main/java/com/sammaru5/sammaru/domain/SearchSubject.java
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
  src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
  src/test/java/com/sammaru5/sammaru/repository/ArticlesSearchTest.java
Labels: API, FEAT

#59 fix: 회원 정보 수정 기능 client에 맞게 수정 (#58)
  src/main/java/com/sammaru5/sammaru/domain/User.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/web/request/UserRequest.java
Labels: FIX, API
