Repository SAMMaru5/SAMMaruServer, pull requests merged in 2022-09, with the labels that each got.

#81 bug: Value Annotation 사용 필드에서 static 제거 (#80)
  src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
Labels: BUG, FIX

#87 bug: 인증 관련 오류 해결
  src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
  src/main/java/com/sammaru5/sammaru/config/security/UserDetail.java
Labels: BUG

#85 fix: username으로 검색 시, 검색 글자가 포함된 모든 users를 List로 출력되도록 수정
  src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
Labels: FIX

#94 fix: request가 들어왔을 때 AccessToken 값을 Cookie가 아닌 header에서 확인하도록 변경
  src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
Labels: BUG

#96 fix: 유저 포인트 추가할 때 500 에러 해결
  src/main/java/com/sammaru5/sammaru/web/request/PointRequest.java
Labels: FIX

#90 feat: 페이징 API 기능 추가
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
  src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
  src/test/java/com/sammaru5/sammaru/repository/ArticlesSearchTest.java
Labels: FEAT

#97 feat: 기수 설정 기능 추가
  src/main/java/com/sammaru5/sammaru/domain/User.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
  src/main/java/com/sammaru5/sammaru/web/request/GenerationRequest.java
Labels: FEAT

#100 fix: 빈 게시판을 조회하더라도 400 error가 발생하지 않고 200 OK로 빈 배열을 반환하도록 수정
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
Labels: FIX, API

#101 feat: 학년 정보 변수 생성 및 설정 기능 추가
  src/main/java/com/sammaru5/sammaru/domain/User.java
  src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
  src/main/java/com/sammaru5/sammaru/web/request/UserRequest.java
Labels: FEAT

#89 bug: 본인의 회원정보 조회시 DB에서 해당 정보를 가져오도록 수정
  src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
  src/main/java/com/sammaru5/sammaru/config/security/SecurityUtil.java
  src/main/java/com/sammaru5/sammaru/config/security/UserDetail.java
  src/main/java/com/sammaru5/sammaru/domain/User.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
  src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
Labels: BUG

#103 feat: 게시글 좋아요 수정 기능 추가
  build.gradle
  src/main/java/com/sammaru5/sammaru/config/RedisConfig.java
  src/main/java/com/sammaru5/sammaru/domain/Article.java
  src/main/java/com/sammaru5/sammaru/domain/ArticleLike.java
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/repository/ArticleLikeRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleLikeService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
  src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
  src/test/java/com/sammaru5/sammaru/WithMockCustomUser.java
  src/test/java/com/sammaru5/sammaru/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/sammaru5/sammaru/repository/ArticleLikeRepositoryTest.java
  src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
  src/test/java/com/sammaru5/sammaru/repository/ArticlesSearchTest.java
  src/test/java/com/sammaru5/sammaru/service/article/ArticleLikeServiceTest.java
  src/test/java/com/sammaru5/sammaru/service/article/ArticleRemoveServiceTest.java
  src/test/java/com/sammaru5/sammaru/service/article/ArticleSearchServiceTest.java
  src/test/resources/application.yml
Labels: FEAT

#111 feat: 로그아웃 API 추가
  src/main/java/com/sammaru5/sammaru/config/SwaggerConfig.java
  src/main/java/com/sammaru5/sammaru/service/user/UserLogoutService.java
  src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
Labels: FEAT

#113 fix: CommentDTO수정 (createDt, author추가)
  src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
Labels: API
