Repository SAMMaru5/SAMMaruServer, pull requests merged in 2022-08, with the labels that each got.

#63 fix : 자기 자신의 회원 정보 조회 API를 임시 회원도 사용할 수 있게 변경
  src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
Labels: FIX

#61 refactor : 서비스 간 의존성과 결합도를 낮추는 리팩토링 진행
  src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
  src/main/java/com/sammaru5/sammaru/repository/BoardRepository.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
  src/main/java/com/sammaru5/sammaru/service/article/ArticleStatusService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardRemoveService.java
  src/main/java/com/sammaru5/sammaru/service/board/BoardStatusService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
  src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
  src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
Labels: REFACTOR

#65 refactor : UserAuthority에 @Enumerated(value = EnumType.STRING) 적용
  src/main/java/com/sammaru5/sammaru/domain/User.java
Labels: REFACTOR

#73 refactor: content type (varchar->text)로 수정
  src/main/java/com/sammaru5/sammaru/domain/Article.java
  src/main/java/com/sammaru5/sammaru/domain/Comment.java
Labels: REFACTOR

#72 refactor: id값 generateValue strategy IDENTITY로 수정
  src/main/java/com/sammaru5/sammaru/domain/Article.java
  src/main/java/com/sammaru5/sammaru/domain/Board.java
  src/main/java/com/sammaru5/sammaru/domain/Comment.java
  src/main/java/com/sammaru5/sammaru/domain/File.java
  src/main/java/com/sammaru5/sammaru/domain/Schedule.java
Labels: REFACTOR

#70 fix: CustomException 발생시 Http Response의 Http Status Code가 해당 exception과 일치하도록 수정
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/web/controller/exception/ExceptionController.java
Labels: FIX

#74 refactor : JWT 인증 방식 변경 및 로그인, Reissue 방식 변경
  build.gradle
  src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
  src/main/java/com/sammaru5/sammaru/config/jwt/AccessTokenResponseDto.java
  src/main/java/com/sammaru5/sammaru/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sammaru5/sammaru/config/jwt/JwtTokenProvider.java
  src/main/java/com/sammaru5/sammaru/config/jwt/TokenDto.java
  src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
  src/main/java/com/sammaru5/sammaru/config/security/CustomUserDetailsService.java
  src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
  src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
  src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
  src/main/java/com/sammaru5/sammaru/util/redis/RedisUtil.java
  src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
  src/main/java/com/sammaru5/sammaru/web/request/SignInRequest.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: API, REFACTOR
